import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

/**
 * Adds <link rel="preload" as="style"> for CSS files generated by Vite,
 * so the browser starts fetching CSS before it encounters the <link rel="stylesheet">.
 */
function cssPreloadPlugin(): Plugin {
  return {
    name: "css-preload",
    enforce: "post",
    transformIndexHtml(html) {
      const cssLinks = [...html.matchAll(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+\.css)"[^>]*>/g)];
      if (!cssLinks.length) return html;

      const preloadTags = cssLinks
        .map(([, href]) => `<link rel="preload" href="${href}" as="style">`)
        .join("\n    ");

      return html.replace("</head>", `    ${preloadTags}\n  </head>`);
    },
  };
}

/**
 * Pre-renders a static index.html for each route after vite build.
 * Each file gets unique <title>, <meta description>, canonical and OG tags -
 * so crawlers see per-page HTML without needing a JS runtime.
 */
function prerenderPlugin(): Plugin {
  const BASE_URL = "https://www.ortzat.co.il";
  type RouteMeta = { path: string; title: string; description: string; robots?: string };

  const routes: RouteMeta[] = [
    {
      path: "/",
      title: "המוסך של צביקה | מוסך מקצועי בירושלים - אור-צת שירותי רכב",
      description:
        "המוסך של צביקה - מוסך מקצועי בירושלים, גבעת שאול. מעל 30 שנות ניסיון במכונאות רכב, דיאגנוסטיקה ממוחשבת, מיזוג אוויר והכנה לטסט. שקיפות מלאה, מחיר הוגן ושירות אישי. 02-6514446.",
    },
    {
      path: "/services",
      title: "שירותי מוסך מקצועיים בירושלים | המוסך של צביקה",
      description:
        "שירותי מכונאות רכב מקיפים בירושלים: טיפולים שוטפים, דיאגנוסטיקה ממוחשבת, מיזוג אוויר לרכב, הכנה לטסט שנתי, בדיקת רכב לפני קנייה ועוד. מעל 30 שנות ניסיון. 02-6514446.",
    },
    {
      path: "/about",
      title: "אודות המוסך של צביקה | מוסך משפחתי בירושלים מאז 1993",
      description:
        "הכירו את המוסך של צביקה - מוסך משפחתי בגבעת שאול, ירושלים. מעל 30 שנות ניסיון, שירות אישי ושקיפות מלאה. הסיפור שלנו, הערכים שמנחים אותנו והצוות.",
    },
    {
      path: "/gallery",
      title: "גלריית תמונות | המוסך של צביקה - ירושלים",
      description:
        "צפו בתמונות מהמוסך של צביקה בגבעת שאול, ירושלים. מוסך מקצועי, מצויד ומסודר עם ציוד מתקדם לטיפול ברכב.",
    },
    {
      path: "/contact",
      title: "צור קשר | המוסך של צביקה - ירושלים",
      description:
        "צרו קשר עם המוסך של צביקה בגבעת שאול, ירושלים. טלפון: 02-6514446, וואטסאפ: 052-651-4446. רחוב האופה 4. שעות פעילות: א׳-ה׳ 08:00-16:30.",
    },
    {
      path: "/faq",
      title: "שאלות נפוצות | המוסך של צביקה - ירושלים",
      description:
        "תשובות לשאלות נפוצות על שירותי המוסך של צביקה: עלויות טיפול, הכנה לטסט, זמני טיפול, סוגי רכבים ועוד. מוסך מקצועי בירושלים מאז 1993.",
    },
    {
      path: "/blog",
      title: "בלוג | טיפים ומדריכים לטיפול ברכב - המוסך של צביקה",
      description:
        "מאמרים מקצועיים על טיפול ברכב: איך לבחור מוסך, הכנה לטסט, החלפת שמן, מיזוג אוויר, סימני אזהרה ועוד. טיפים מהמוסך של צביקה בירושלים.",
    },
    {
      path: "/privacy",
      title: "מדיניות פרטיות | המוסך של צביקה - אור-צת שירותי רכב",
      description:
        "מדיניות הפרטיות של המוסך של צביקה - אור-צת שירותי רכב. מידע על איסוף, שימוש והגנה על מידע אישי בהתאם לחוק הגנת הפרטיות.",
      robots: "noindex, follow",
    },
    {
      path: "/accessibility",
      title: "הצהרת נגישות | המוסך של צביקה - אור-צת שירותי רכב",
      description:
        "הצהרת הנגישות של אתר המוסך של צביקה. מחויבות להנגשת האתר לאנשים עם מוגבלויות בהתאם לתקנות הנגישות.",
      robots: "noindex, follow",
    },
    // Blog articles
    {
      path: "/blog/איך-לבחור-מוסך-אמין-בירושלים",
      title: "איך לבחור מוסך אמין בירושלים | בלוג המוסך של צביקה",
      description: "מחפשים מוסך אמין בירושלים? מדריך מקיף עם טיפים מעשיים לבחירת מוסך מקצועי, שקוף והוגן באזור ירושלים וגבעת שאול.",
    },
    {
      path: "/blog/סימנים-שהרכב-צריך-טיפול",
      title: "סימנים שהרכב צריך טיפול | בלוג המוסך של צביקה",
      description: "אל תתעלמו מסימני אזהרה ברכב. מדריך לזיהוי 8 סימנים שמעידים שהרכב שלכם צריך טיפול דחוף במוסך.",
    },
    {
      path: "/blog/כמה-עולה-טיפול-לרכב",
      title: "כמה עולה טיפול לרכב | בלוג המוסך של צביקה",
      description: "תוהים כמה עולה טיפול לרכב? מדריך מפורט על עלויות טיפולים שוטפים, מה משפיע על המחיר, ואיך לחסוך בטיפולי רכב.",
    },
    {
      path: "/blog/מתי-לבדוק-מזגן-ברכב",
      title: "מתי צריך לבדוק מזגן ברכב ואיך לשמור עליו | בלוג המוסך של צביקה",
      description: "המזגן ברכב לא מקרר? מדריך מקיף על תחזוקת מזגן רכב, סימני אזהרה, ומתי להגיע למוסך לבדיקה.",
    },
    {
      path: "/blog/איך-לעבור-טסט-בקלות",
      title: "איך להתכונן לטסט לרכב ולעבור בקלות | בלוג המוסך של צביקה",
      description: "מתכוננים לטסט השנתי? מדריך מלא עם רשימת בדיקות, טיפים לעבור בפעם הראשונה, ומה עושים אם הרכב נכשל.",
    },
    {
      path: "/blog/רעשים-חריגים-ברכב-מה-הם-אומרים",
      title: "רעשים חריגים ברכב: מה הם אומרים ומתי לדאוג | בלוג המוסך של צביקה",
      description: "שומעים רעש מוזר מהרכב? מדריך מקיף לזיהוי רעשים חריגים ברכב, מה הסיבות האפשריות, ומתי חייבים להגיע למוסך בירושלים.",
    },
    {
      path: "/blog/נורת-צק-אנגין-מה-לעשות",
      title: "נורת צ׳ק אנג׳ין - מה לעשות | בלוג המוסך של צביקה",
      description: "נורת הצ'ק אנג'ין נדלקה ברכב? מדריך מעשי עם הסיבות הנפוצות, מתי זה דחוף ומתי פחות, ומה לעשות צעד אחר צעד.",
    },
    {
      path: "/blog/החלפת-שמן-מנוע-למה-חשוב-ומתי",
      title: "החלפת שמן מנוע - למה חשוב ומתי | בלוג המוסך של צביקה",
      description: "מתי צריך להחליף שמן מנוע? מדריך מעשי על סוגי שמנים, תדירות החלפה, מה קורה אם מזניחים, וכמה זה עולה במוסך בירושלים.",
    },
    {
      path: "/blog/רכב-מתחמם-סיבות-ופתרונות",
      title: "רכב מתחמם - סיבות ופתרונות | בלוג המוסך של צביקה",
      description: "מחוג הטמפרטורה עולה? מדריך מעשי על התחממות יתר של מנוע רכב - למה זה קורה, מה לעשות ברגע שזה קורה, ואיך למנוע את זה.",
    },
    {
      path: "/blog/למה-הרכב-צורך-יותר-דלק",
      title: "למה הרכב צורך יותר דלק | בלוג המוסך של צביקה",
      description: "הרכב שותה יותר דלק מהרגיל? מדריך מעשי על 8 סיבות נפוצות לצריכת דלק גבוהה ברכב, ואיך לחסוך כסף בתדלוק.",
    },
  ];

  function escapeAttr(str: string): string {
    return str.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
  }

  const breadcrumbNames: Record<string, string> = {
    "/services": "שירותים",
    "/about": "אודות",
    "/gallery": "גלריה",
    "/contact": "צור קשר",
    "/faq": "שאלות נפוצות",
    "/blog": "בלוג",
    "/privacy": "מדיניות פרטיות",
    "/accessibility": "הצהרת נגישות",
  };

  const h1Map: Record<string, string> = {
    "/services": "שירותי המוסך",
    "/about": "אודות המוסך",
    "/gallery": "הגלריה שלנו",
    "/contact": "צרו קשר עם המוסך",
    "/faq": "שאלות נפוצות",
    "/blog": "הבלוג שלנו",
    "/privacy": "מדיניות פרטיות",
    "/accessibility": "הצהרת נגישות",
  };

  const faqEntities = [
    { "@type": "Question", name: "כמה עולה טיפול שוטף לרכב?", acceptedAnswer: { "@type": "Answer", text: "המחיר תלוי בסוג הרכב, בשנת הייצור ובסוג הטיפול הנדרש. טיפול שוטף בסיסי (החלפת שמן ופילטרים) עולה בדרך כלל סביב 700 ש\"ח. אצלנו במוסך בגבעת שאול, ירושלים, נציג לכם הערכת מחיר לפני שמתחילים לעבוד." } },
    { "@type": "Question", name: "כל כמה זמן צריך לעשות טיפול לרכב?", acceptedAnswer: { "@type": "Answer", text: "ההמלצה הכללית היא טיפול כל 10,000-15,000 ק\"מ או פעם בשנה, לפי המוקדם מביניהם. רכבים ישנים יותר או רכבים שנוסעים בעיקר בעיר (כמו בירושלים) ייתכן שיצטרכו טיפולים תכופים יותר." } },
    { "@type": "Question", name: "איך אפשר לדעת שהרכב צריך טיפול?", acceptedAnswer: { "@type": "Answer", text: "סימנים שכדאי לשים לב אליהם: נורית אזהרה שנדלקת, רעשים חריגים מהמנוע, רטט בהגה, בלמים שמגיבים לאט, צריכת דלק גבוהה מהרגיל, או דליפות מתחת לרכב." } },
    { "@type": "Question", name: "איך מתכוננים לטסט שנתי?", acceptedAnswer: { "@type": "Answer", text: "לפני הטסט כדאי לוודא שהפנסים תקינים, המגבים עובדים, הצמיגים לא שחוקים, הבלמים תקינים, ואין דליפות שמן. אצלנו במוסך עושים בדיקת פרה-טסט מקיפה." } },
    { "@type": "Question", name: "מתי צריך לבדוק את המזגן ברכב?", acceptedAnswer: { "@type": "Answer", text: "אם המזגן לא מקרר כמו פעם, מוציא ריח לא נעים, או משמיע רעשים מוזרים, הגיע הזמן לבדיקה. מומלץ לבדוק את המזגן לפני הקיץ." } },
    { "@type": "Question", name: "מה ההבדל בין מוסך מורשה למוסך עצמאי?", acceptedAnswer: { "@type": "Answer", text: "מוסך מורשה עובד עם יבואן ספציפי ומחויב למחירון שלו. מוסך עצמאי כמו שלנו יכול לטפל בכל סוגי הרכבים, להשתמש בחלקים איכותיים, ולהציע מחירים תחרותיים יותר." } },
    { "@type": "Question", name: "אתם מטפלים בכל סוגי הרכבים?", acceptedAnswer: { "@type": "Answer", text: "כן. אנחנו מטפלים ברכבים פרטיים מכל היצרנים: יונדאי, טויוטה, מאזדה, קיה, סקודה, פולקסווגן, ועוד." } },
    { "@type": "Question", name: "כמה זמן לוקח טיפול שוטף?", acceptedAnswer: { "@type": "Answer", text: "טיפול שוטף בסיסי (שמן ופילטרים) לוקח בדרך כלל כשעה עד שעתיים. טיפולים מורכבים יותר יכולים לקחת יום עבודה." } },
    { "@type": "Question", name: "איפה אתם נמצאים?", acceptedAnswer: { "@type": "Answer", text: "המוסך נמצא ברחוב האופה 4, גבעת שאול, ירושלים. קל להגיע אלינו מכל חלקי העיר." } },
    { "@type": "Question", name: "אפשר לתאם ביקור גם בוואטסאפ?", acceptedAnswer: { "@type": "Answer", text: "בהחלט. שלחו לנו הודעה עם פרטי הרכב ומה הבעיה, ונחזור אליכם עם זמן פנוי קרוב." } },
    { "@type": "Question", name: "האם יש אחריות על העבודה?", acceptedAnswer: { "@type": "Answer", text: "כן. אנחנו נותנים אחריות על כל עבודה שאנחנו מבצעים, כולל חלקי חילוף." } },
  ];

  function getH1(path: string, title: string): string {
    if (path.startsWith("/blog/")) return title.split(" | ")[0] || "בלוג";
    return h1Map[path] || "המוסך של צביקה - מוסך מקצועי בירושלים";
  }

  function buildStaticSchemas(route: RouteMeta, canonicalUrl: string): string {
    const scripts: string[] = [];

    if (route.path !== "/") {
      const items: Array<{ "@type": string; position: number; name: string; item?: string }> = [
        { "@type": "ListItem", position: 1, name: "דף הבית", item: `${BASE_URL}/` },
      ];

      if (route.path.startsWith("/blog/")) {
        items.push({ "@type": "ListItem", position: 2, name: "בלוג", item: `${BASE_URL}/blog` });
        items.push({ "@type": "ListItem", position: 3, name: route.title.split(" | ")[0] || route.title });
      } else if (breadcrumbNames[route.path]) {
        items.push({ "@type": "ListItem", position: 2, name: breadcrumbNames[route.path], item: canonicalUrl });
      }

      scripts.push(`<script type="application/ld+json">${JSON.stringify({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: items,
      })}</script>`);
    }

    if (route.path === "/faq") {
      scripts.push(`<script type="application/ld+json">${JSON.stringify({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faqEntities,
      })}</script>`);
    }

    return scripts.join("\n    ");
  }

  function patchHtml(html: string, route: RouteMeta): string {
    const canonicalUrl = route.path === "/" ? `${BASE_URL}/` : `${BASE_URL}${route.path}`;
    const t = escapeAttr(route.title);
    const d = escapeAttr(route.description);
    const u = escapeAttr(canonicalUrl);
    const h1 = escapeAttr(getH1(route.path, route.title));
    const extraSchemas = buildStaticSchemas(route, canonicalUrl);

    let patched = html
      .replace(/<title>[^<]*<\/title>/, `<title>${route.title}</title>`)
      .replace(/(<meta\s+name="description"\s+content=")[^"]*(")/,  `$1${d}$2`)
      .replace(/(<link\s+rel="canonical"\s+[^>]*href=")[^"]*(")/,   `$1${u}$2`)
      .replace(/(<meta\s+property="og:title"\s+content=")[^"]*(")/,       `$1${t}$2`)
      .replace(/(<meta\s+property="og:description"\s+content=")[^"]*(")/,  `$1${d}$2`)
      .replace(/(<meta\s+property="og:url"\s+content=")[^"]*(")/,         `$1${u}$2`)
      .replace(/(<meta\s+name="twitter:title"\s+content=")[^"]*(")/,       `$1${t}$2`)
      .replace(/(<meta\s+name="twitter:description"\s+content=")[^"]*(")/,  `$1${d}$2`)
      .replace(/(<h1[^>]*id="seo-h1"[^>]*>)[^<]*(<\/h1>)/, `$1${h1}$2`);

    if (route.robots) {
      patched = patched.replace(/(<meta\s+name="robots"\s+content=")[^"]*(")/, `$1${escapeAttr(route.robots)}$2`);
    }

    if (extraSchemas) {
      patched = patched.replace("</head>", `    ${extraSchemas}\n  </head>`);
    }

    return patched;
  }

  return {
    name: "prerender-routes",
    enforce: "post",
    closeBundle() {
      const distDir = join(process.cwd(), "dist");
      let baseHtml: string;
      try {
        baseHtml = readFileSync(join(distDir, "index.html"), "utf-8");
      } catch {
        console.warn("[prerender] dist/index.html not found - skipping.");
        return;
      }

      for (const route of routes) {
        const patched = patchHtml(baseHtml, route);
        if (route.path === "/") {
          writeFileSync(join(distDir, "index.html"), patched, "utf-8");
          console.log(`[prerender] ✓ /`);
        } else {
          const dir = join(distDir, route.path.slice(1));
          mkdirSync(dir, { recursive: true });
          writeFileSync(join(dir, "index.html"), patched, "utf-8");
          console.log(`[prerender] ✓ ${route.path}`);
        }
      }
      console.log(`[prerender] ✅ ${routes.length} pages pre-rendered`);
    },
  };
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    react(),
    cssPreloadPlugin(),
    mode === "development" && componentTagger(),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          "vendor-react": ["react", "react-dom"],
          "vendor-router": ["react-router-dom"],
          "vendor-query": ["@tanstack/react-query"],
        },
      },
    },
    target: "es2020",
    cssMinify: true,
  },
}));
