import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

/**
 * Adds <link rel="preload" as="style"> for CSS files generated by Vite,
 * so the browser starts fetching CSS before it encounters the <link rel="stylesheet">.
 */
function cssPreloadPlugin(): Plugin {
  return {
    name: "css-preload",
    enforce: "post",
    transformIndexHtml(html) {
      const cssLinks = [...html.matchAll(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+\.css)"[^>]*>/g)];
      if (!cssLinks.length) return html;

      const preloadTags = cssLinks
        .map(([, href]) => `<link rel="preload" href="${href}" as="style">`)
        .join("\n    ");

      return html.replace("</head>", `    ${preloadTags}\n  </head>`);
    },
  };
}

/**
 * Pre-renders a static index.html for each route after vite build.
 * Each file gets unique <title>, <meta description>, canonical and OG tags -
 * so crawlers see per-page HTML without needing a JS runtime.
 */
function prerenderPlugin(): Plugin {
  const BASE_URL = "https://www.ortzat.co.il";
  type RouteMeta = { path: string; title: string; description: string; robots?: string; date?: string };

  const routes: RouteMeta[] = [
    { path: "/", title: "המוסך של צביקה | מוסך מקצועי בירושלים - אור-צת שירותי רכב", description: "המוסך של צביקה - מוסך מקצועי בירושלים, גבעת שאול. מעל 30 שנות ניסיון במכונאות רכב, דיאגנוסטיקה ממוחשבת, מיזוג אוויר והכנה לטסט. שקיפות מלאה, מחיר הוגן ושירות אישי. 02-6514446." },
    { path: "/services", title: "שירותי מוסך בירושלים | רשימת השירותים המלאה - המוסך של צביקה", description: "כל שירותי המוסך של צביקה בגבעת שאול, ירושלים: טיפולים שוטפים, דיאגנוסטיקה ממוחשבת, מיזוג אוויר, הכנה לטסט, בדיקת רכב לפני קנייה, טיפול בבעיות חשמל ומנוע. 02-6514446." },
    { path: "/about", title: "אודות המוסך של צביקה | מי אנחנו ולמה לבחור בנו", description: "הכירו את הצוות מאחורי המוסך של צביקה בגבעת שאול, ירושלים. מוסך משפחתי מאז 1993, מעל 30 שנות ניסיון, שקיפות מלאה ומקצועיות ללא פשרות. למה אלפי לקוחות סומכים עלינו." },
    { path: "/gallery", title: "הגלריה שלנו | המוסך של צביקה בגבעת שאול, ירושלים", description: "עמוד הגלריה של המוסך של צביקה בגבעת שאול, ירושלים. תמונות נוספות בדרך - בינתיים תוכלו לראות את חזית המוסך וליצור קשר בטלפון או בוואטסאפ. 02-6514446." },
    { path: "/contact", title: "צור קשר | טלפון, וואטסאפ והגעה למוסך של צביקה בירושלים", description: "צרו קשר עם המוסך של צביקה בגבעת שאול, ירושלים. טלפון: 02-6514446, וואטסאפ: 052-651-4446, כתובת: רחוב האופה 4. ניווט ב-Waze, שעות פעילות ואפשרות להשאיר פרטים." },
    { path: "/faq", title: "שאלות נפוצות | המוסך של צביקה - ירושלים", description: "תשובות לשאלות נפוצות על שירותי המוסך של צביקה: עלויות טיפול, הכנה לטסט, זמני טיפול, סוגי רכבים ועוד. מוסך מקצועי בירושלים מאז 1993." },
    { path: "/blog", title: "טיפים, תקלות ותחזוקת רכב | בלוג המוסך של צביקה - ירושלים", description: "מדריכים מעשיים על תחזוקת רכב, זיהוי תקלות, הכנה לטסט, החלפת שמן, מיזוג אוויר, רעשים חריגים ועוד. טיפים מקצועיים מהמוסך של צביקה בירושלים." },
    { path: "/privacy", title: "מדיניות פרטיות | המוסך של צביקה (אור-צת)", description: "מדיניות הפרטיות של המוסך של צביקה (אור-צת). מידע על איסוף, שימוש והגנה על מידע אישי בהתאם לחוק הגנת הפרטיות.", robots: "noindex, follow" },
    { path: "/accessibility", title: "הצהרת נגישות | המוסך של צביקה (אור-צת)", description: "הצהרת הנגישות של אתר המוסך של צביקה. מחויבות להנגשת האתר לאנשים עם מוגבלויות בהתאם לתקנות הנגישות.", robots: "noindex, follow" },
    // Blog articles - synced with index.html inline script & src/data/blog-articles.ts
    { path: "/blog/איך-לבחור-מוסך-אמין-בירושלים", title: "איך לבחור מוסך אמין בירושלים | בלוג המוסך של צביקה", description: "מחפשים מוסך אמין בירושלים? מדריך מקיף עם טיפים מעשיים לבחירת מוסך מקצועי, שקוף והוגן באזור ירושלים וגבעת שאול.", date: "2024-12-15" },
    { path: "/blog/סימנים-שהרכב-צריך-טיפול", title: "סימנים שהרכב צריך טיפול מיידי | בלוג המוסך של צביקה", description: "אל תתעלמו מסימני אזהרה ברכב. מדריך לזיהוי 8 סימנים שמעידים שהרכב שלכם צריך טיפול דחוף במוסך.", date: "2024-12-10" },
    { path: "/blog/כמה-עולה-טיפול-לרכב", title: "כמה עולה טיפול לרכב ומה משפיע על המחיר | בלוג המוסך של צביקה", description: "תוהים כמה עולה טיפול לרכב? מדריך מפורט על עלויות טיפולים שוטפים, מה משפיע על המחיר, ואיך לחסוך בטיפולי רכב.", date: "2024-12-05" },
    { path: "/blog/מתי-לבדוק-מזגן-ברכב", title: "מתי צריך לבדוק מזגן ברכב ואיך לשמור עליו | בלוג המוסך של צביקה", description: "המזגן ברכב לא מקרר? מדריך מקיף על תחזוקת מזגן רכב, סימני אזהרה, ומתי להגיע למוסך לבדיקה.", date: "2024-11-28" },
    { path: "/blog/איך-לעבור-טסט-בקלות", title: "איך להתכונן לטסט לרכב ולעבור בקלות | בלוג המוסך של צביקה", description: "מתכוננים לטסט השנתי? מדריך מלא עם רשימת בדיקות, טיפים לעבור בפעם הראשונה, ומה עושים אם הרכב נכשל.", date: "2024-11-20" },
    { path: "/blog/רעשים-חריגים-ברכב-מה-הם-אומרים", title: "רעשים חריגים ברכב: מה הם אומרים ומתי לדאוג | בלוג המוסך של צביקה", description: "שומעים רעש מוזר מהרכב? מדריך מקיף לזיהוי רעשים חריגים ברכב, מה הסיבות האפשריות, ומתי חייבים להגיע למוסך בירושלים.", date: "2025-03-28" },
    { path: "/blog/נורת-צק-אנגין-מה-לעשות", title: "נורת צ׳ק אנג׳ין נדלקה? מה זה אומר ומה לעשות | בלוג המוסך של צביקה", description: "נורת הצ'ק אנג'ין נדלקה ברכב? מדריך מעשי עם הסיבות הנפוצות, מתי זה דחוף ומתי פחות, ומה לעשות צעד אחר צעד.", date: "2025-03-28" },
    { path: "/blog/החלפת-שמן-מנוע-למה-חשוב-ומתי", title: "החלפת שמן מנוע: למה זה קריטי ומתי צריך להחליף | בלוג המוסך של צביקה", description: "מתי צריך להחליף שמן מנוע? מדריך מעשי על סוגי שמנים, תדירות החלפה, מה קורה אם מזניחים, וכמה זה עולה במוסך בירושלים.", date: "2025-03-28" },
    { path: "/blog/רכב-מתחמם-סיבות-ופתרונות", title: "הרכב מתחמם? סיבות נפוצות ומה לעשות מיד | בלוג המוסך של צביקה", description: "מחוג הטמפרטורה עולה? מדריך מעשי על התחממות יתר של מנוע רכב - למה זה קורה, מה לעשות ברגע שזה קורה, ואיך למנוע את זה.", date: "2025-03-28" },
    { path: "/blog/למה-הרכב-צורך-יותר-דלק", title: "למה הרכב צורך יותר דלק ואיך לתקן את זה | בלוג המוסך של צביקה", description: "הרכב שותה יותר דלק מהרגיל? מדריך מעשי על 8 סיבות נפוצות לצריכת דלק גבוהה ברכב, ואיך לחסוך כסף בתדלוק.", date: "2025-03-28" },
    { path: "/blog/מתי-להחליף-מצבר-לרכב", title: "מתי להחליף מצבר לרכב ואיך לדעת שהוא גמור | בלוג המוסך של צביקה", description: "הרכב לא מתניע? מדריך מעשי על סימנים שהמצבר עומד להיגמר, כמה זמן מצבר מחזיק, כמה עולה החלפה, ואיך לשמור עליו.", date: "2025-03-28" },
    { path: "/blog/מתי-להחליף-בלמים-ברכב", title: "מתי להחליף בלמים ברכב וכמה זה עולה | בלוג המוסך של צביקה", description: "שומעים חריקה בבלימה? מדריך מעשי על סימנים שהבלמים צריכים החלפה, סוגי בלמים, עלויות, ומתי זה דחוף.", date: "2025-03-28" },
    { path: "/blog/בדיקת-רכב-לפני-קנייה", title: "בדיקת רכב לפני קנייה: מה חייבים לבדוק ולמה | בלוג המוסך של צביקה", description: "קונים רכב יד שנייה? מדריך מקיף על מה לבדוק לפני שסוגרים עסקה, סימנים שמשהו לא בסדר, ולמה חשובה בדיקה במוסך.", date: "2025-03-28" },
    { path: "/blog/כמה-זמן-לוקח-טיפול-במוסך", title: "כמה זמן לוקח טיפול במוסך ומה משפיע על זמן ההמתנה | בלוג המוסך של צביקה", description: "תוהים כמה זמן תהיו בלי רכב? מדריך מעשי על זמני טיפול במוסך לפי סוג הטיפול, ואיך לתכנן את הביקור.", date: "2025-03-28" },
    { path: "/blog/טיפול-ברכב-היברידי", title: "טיפול ברכב היברידי: מה שונה ומה צריך לדעת | בלוג המוסך של צביקה", description: "יש לכם רכב היברידי? מדריך מעשי על תחזוקת רכב היברידי, מה שונה מרכב רגיל, מה עולה יותר, ומה דווקא זול יותר.", date: "2025-03-28" },
    { path: "/blog/תחזוקת-רכב-בירושלים", title: "תחזוקת רכב בירושלים: מה שונה ולמה זה חשוב | בלוג המוסך של צביקה", description: "גרים בירושלים? הרכב שלכם עובד קשה יותר. מדריך על תחזוקת רכב מותאמת לנסיעה בעיר עם עליות תלולות, פקקים ומזג אוויר קיצוני.", date: "2025-03-28" },
    { path: "/blog/מקורי-מול-גנרי-חלקי-חילוף-לרכב", title: "מקורי מול גנרי: מה ההבדל האמיתי ולמה אתה משלם פי 2.5? | בלוג המוסך של צביקה", description: "חלקי חילוף מקוריים לעומת גנריים - האם יש הבדל אמיתי? המדריך שיסביר לכם מי באמת מייצר את חלקי הרכב, ומתי גנרי הוא לא רק טוב, אלא עדיף.", date: "2026-04-03" },
    { path: "/blog/הרכב-בחורף-בעיות-ומניעה", title: "הרכב שלכם מוכן לחורף? 4 בעיות שהחורף גורם ואיך למנוע אותן | בלוג המוסך של צביקה", description: "בעיות חשמל, קשיי התנעה, עלים שסותמים את האוורור - הנה מה שקורה לרכב בחורף ואיך להתכונן נכון לפני שהגשם מתחיל.", date: "2026-04-03" },
    { path: "/blog/מזגן-לא-מחמם-בחורף-הסבר-ופתרון", title: "המזגן לא מחמם בחורף? ההסבר הפשוט ולמה זה לא באמת המזגן | בלוג המוסך של צביקה", description: "כל חורף אנחנו שומעים את אותה שאלה: המזגן לא מחמם. ההסבר: מזגן ברכב מקרר בלבד. החימום הוא מערכת אחרת לגמרי. הנה איך זה עובד ומה לעשות כשזה מתקלקל.", date: "2026-04-03" },
    { path: "/blog/אחריות-על-רכב-חדש-זכויות-שלא-ידעתם", title: "אחריות על רכב חדש: הזכות שרוב הנהגים לא יודעים שיש להם | בלוג המוסך של צביקה", description: "האם חייבים לטפל ביבואן מורשה כדי לא לאבד את אחריות הרכב? לא. חוק ישראלי מגן עליכם. כל מה שצריך לדעת על זכויות האחריות, ומה המוסך המורשה לא ממהר לספר לכם.", date: "2026-04-03" },
  ];

  function escapeAttr(str: string): string {
    return str.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
  }

  const breadcrumbNames: Record<string, string> = {
    "/services": "שירותים",
    "/about": "אודות",
    "/gallery": "גלריה",
    "/contact": "צור קשר",
    "/faq": "שאלות נפוצות",
    "/blog": "בלוג",
    "/privacy": "מדיניות פרטיות",
    "/accessibility": "הצהרת נגישות",
  };

  const h1Map: Record<string, string> = {
    "/services": "שירותי המוסך",
    "/about": "אודות המוסך",
    "/gallery": "הגלריה שלנו",
    "/contact": "צרו קשר עם המוסך",
    "/faq": "שאלות נפוצות",
    "/blog": "הבלוג שלנו",
    "/privacy": "מדיניות פרטיות",
    "/accessibility": "הצהרת נגישות",
  };

  const faqEntities = [
    { "@type": "Question", name: "כמה עולה טיפול שוטף לרכב?", acceptedAnswer: { "@type": "Answer", text: "המחיר תלוי בסוג הרכב, בשנת הייצור ובסוג הטיפול הנדרש. טיפול שוטף בסיסי (החלפת שמן ופילטרים) עולה בדרך כלל בין 250 ל-500 ש\"ח. אצלנו במוסך בגבעת שאול, ירושלים, תמיד נציג מראש את המחיר המדויק לפני שמתחילים לעבוד." } },
    { "@type": "Question", name: "כל כמה זמן צריך לעשות טיפול לרכב?", acceptedAnswer: { "@type": "Answer", text: "ההמלצה הכללית היא טיפול כל 10,000-15,000 ק\"מ או פעם בשנה, לפי המוקדם מביניהם. רכבים ישנים יותר או רכבים שנוסעים בעיקר בעיר (כמו בירושלים) ייתכן שיצטרכו טיפולים תכופים יותר." } },
    { "@type": "Question", name: "איך אפשר לדעת שהרכב צריך טיפול?", acceptedAnswer: { "@type": "Answer", text: "סימנים שכדאי לשים לב אליהם: נורית אזהרה שנדלקת, רעשים חריגים מהמנוע, רטט בהגה, בלמים שמגיבים לאט, צריכת דלק גבוהה מהרגיל, או דליפות מתחת לרכב." } },
    { "@type": "Question", name: "איך מתכוננים לטסט שנתי?", acceptedAnswer: { "@type": "Answer", text: "לפני הטסט כדאי לוודא שהפנסים תקינים, המגבים עובדים, הצמיגים לא שחוקים, הבלמים תקינים, ואין דליפות שמן. אצלנו במוסך עושים בדיקת פרה-טסט מקיפה." } },
    { "@type": "Question", name: "מתי צריך לבדוק את המזגן ברכב?", acceptedAnswer: { "@type": "Answer", text: "אם המזגן לא מקרר כמו פעם, מוציא ריח לא נעים, או משמיע רעשים מוזרים, הגיע הזמן לבדיקה. מומלץ לבדוק את המזגן לפני הקיץ." } },
    { "@type": "Question", name: "מה ההבדל בין מוסך מורשה למוסך עצמאי?", acceptedAnswer: { "@type": "Answer", text: "מוסך מורשה עובד עם יבואן ספציפי ומחויב למחירון שלו. מוסך עצמאי כמו שלנו יכול לטפל בכל סוגי הרכבים, להשתמש בחלקים איכותיים, ולהציע מחירים תחרותיים יותר." } },
    { "@type": "Question", name: "אתם מטפלים בכל סוגי הרכבים?", acceptedAnswer: { "@type": "Answer", text: "כן. אנחנו מטפלים ברכבים פרטיים מכל היצרנים: יונדאי, טויוטה, מאזדה, קיה, סקודה, פולקסווגן, ועוד." } },
    { "@type": "Question", name: "כמה זמן לוקח טיפול שוטף?", acceptedAnswer: { "@type": "Answer", text: "טיפול שוטף בסיסי (שמן ופילטרים) לוקח בדרך כלל כשעה עד שעתיים. טיפולים מורכבים יותר יכולים לקחת יום עבודה." } },
    { "@type": "Question", name: "איפה אתם נמצאים?", acceptedAnswer: { "@type": "Answer", text: "המוסך נמצא ברחוב האופה 4, גבעת שאול, ירושלים. קל להגיע אלינו מכל חלקי העיר." } },
    { "@type": "Question", name: "אפשר לתאם ביקור גם בוואטסאפ?", acceptedAnswer: { "@type": "Answer", text: "בהחלט. שלחו לנו הודעה עם פרטי הרכב ומה הבעיה, ונחזור אליכם עם זמן פנוי קרוב." } },
    { "@type": "Question", name: "האם יש אחריות על העבודה?", acceptedAnswer: { "@type": "Answer", text: "כן. אנחנו נותנים אחריות על כל עבודה שאנחנו מבצעים, כולל חלקי חילוף." } },
  ];

  function getH1(path: string, title: string): string {
    if (path.startsWith("/blog/")) return title.split(" | ")[0] || "בלוג";
    return h1Map[path] || "המוסך של צביקה - מוסך מקצועי בירושלים";
  }

  function buildStaticSchemas(route: RouteMeta, canonicalUrl: string): string {
    const scripts: string[] = [];

    if (route.path !== "/") {
      const items: Array<{ "@type": string; position: number; name: string; item?: string }> = [
        { "@type": "ListItem", position: 1, name: "דף הבית", item: `${BASE_URL}/` },
      ];

      if (route.path.startsWith("/blog/")) {
        items.push({ "@type": "ListItem", position: 2, name: "בלוג", item: `${BASE_URL}/blog` });
        items.push({ "@type": "ListItem", position: 3, name: route.title.split(" | ")[0] || route.title });
      } else if (breadcrumbNames[route.path]) {
        items.push({ "@type": "ListItem", position: 2, name: breadcrumbNames[route.path], item: canonicalUrl });
      }

      scripts.push(`<script type="application/ld+json">${JSON.stringify({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: items,
      })}</script>`);
    }

    if (route.path === "/faq") {
      scripts.push(`<script type="application/ld+json">${JSON.stringify({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faqEntities,
      })}</script>`);
    }

    // Article JSON-LD for blog posts
    if (route.path.startsWith("/blog/") && route.date) {
      const articleName = route.title.split(" | ")[0];
      scripts.push(`<script type="application/ld+json">${JSON.stringify({
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        headline: articleName,
        description: route.description,
        datePublished: route.date,
        dateModified: route.date,
        url: canonicalUrl,
        inLanguage: "he",
        author: { "@type": "Organization", name: "המוסך של צביקה (אור-צת)", url: BASE_URL },
        publisher: { "@type": "Organization", name: "המוסך של צביקה (אור-צת)", url: BASE_URL, logo: { "@type": "ImageObject", url: `${BASE_URL}/favicon.png` } },
        mainEntityOfPage: { "@type": "WebPage", "@id": canonicalUrl },
        image: `${BASE_URL}/og-home.jpg`,
      })}</script>`);
    }

    return scripts.join("\n    ");
  }

  function patchHtml(html: string, route: RouteMeta): string {
    const canonicalUrl = route.path === "/" ? `${BASE_URL}/` : `${BASE_URL}${route.path}`;
    const t = escapeAttr(route.title);
    const d = escapeAttr(route.description);
    const u = escapeAttr(canonicalUrl);
    const h1 = escapeAttr(getH1(route.path, route.title));
    const extraSchemas = buildStaticSchemas(route, canonicalUrl);

    let patched = html
      .replace(/<title>[^<]*<\/title>/, `<title>${route.title}</title>`)
      .replace(/(<meta\s+name="description"\s+content=")[^"]*(")/,  `$1${d}$2`)
      .replace(/(<link\s+rel="canonical"\s+[^>]*href=")[^"]*(")/,   `$1${u}$2`)
      .replace(/(<meta\s+property="og:title"\s+content=")[^"]*(")/,       `$1${t}$2`)
      .replace(/(<meta\s+property="og:description"\s+content=")[^"]*(")/,  `$1${d}$2`)
      .replace(/(<meta\s+property="og:url"\s+content=")[^"]*(")/,         `$1${u}$2`)
      .replace(/(<meta\s+name="twitter:title"\s+content=")[^"]*(")/,       `$1${t}$2`)
      .replace(/(<meta\s+name="twitter:description"\s+content=")[^"]*(")/,  `$1${d}$2`)
      .replace(/(<h1[^>]*id="seo-h1"[^>]*>)[^<]*(<\/h1>)/, `$1${h1}$2`);

    if (route.robots) {
      patched = patched.replace(/(<meta\s+name="robots"\s+content=")[^"]*(")/, `$1${escapeAttr(route.robots)}$2`);
    }

    // og:type article for blog posts
    if (route.path.startsWith("/blog/") && route.date) {
      patched = patched.replace(/(<meta\s+property="og:type"\s+content=")[^"]*(")/, `$1article$2`);
    }

    // hreflang
    patched = patched.replace(/(<link\s+rel="alternate"\s+hreflang="he-IL"\s+href=")[^"]*(")/, `$1${u}$2`);
    patched = patched.replace(/(<link\s+rel="alternate"\s+hreflang="x-default"\s+href=")[^"]*(")/, `$1${u}$2`);

    if (extraSchemas) {
      patched = patched.replace("</head>", `    ${extraSchemas}\n  </head>`);
    }

    return patched;
  }

  return {
    name: "prerender-routes",
    enforce: "post",
    closeBundle() {
      const distDir = join(process.cwd(), "dist");
      let baseHtml: string;
      try {
        baseHtml = readFileSync(join(distDir, "index.html"), "utf-8");
      } catch {
        console.warn("[prerender] dist/index.html not found - skipping.");
        return;
      }

      for (const route of routes) {
        const patched = patchHtml(baseHtml, route);
        if (route.path === "/") {
          writeFileSync(join(distDir, "index.html"), patched, "utf-8");
          console.log(`[prerender] ✓ /`);
        } else {
          const dir = join(distDir, route.path.slice(1));
          mkdirSync(dir, { recursive: true });
          writeFileSync(join(dir, "index.html"), patched, "utf-8");
          console.log(`[prerender] ✓ ${route.path}`);
        }
      }
      console.log(`[prerender] ✅ ${routes.length} pages pre-rendered`);
    },
  };
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: Number(process.env.PORT) || 8080,
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    react(),
    cssPreloadPlugin(),
    prerenderPlugin(),
    mode === "development" && componentTagger(),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          "vendor-react": ["react", "react-dom"],
          "vendor-router": ["react-router-dom"],
          "vendor-query": ["@tanstack/react-query"],
        },
      },
    },
    target: "es2020",
    cssMinify: true,
  },
}));
